### ISSUE TITLE
"The value NIL is not of type NUMBER" on startup on Windows

### ISSUE THREAD

**Issue by Zulu-Inuoe** [VitoVan/cl-pkr#1]
Hello,

I just downloaded and ran the executable at https://github.com/VitoVan/cl-pkr/releases/download/1.0.0/color-picker.exe

and got the following:

![image](https://user-images.githubusercontent.com/1526310/60642562-53852700-9dfe-11e9-84db-c076325ab565.png)

This happened when running it for the first time. When I ran it again, it seemed to work correctly. But when then pressing `Control + C` I got
![image](https://user-images.githubusercontent.com/1526310/60642733-de662180-9dfe-11e9-8427-eacb4cc7ff4a.png)

And of course as these things go, the third time I ran it, it seems to be working perfectly.

I'm on Windows 10, x64

**Comment by VitoVan** [comment]
You definitely a tough person, I'll just walk away the first time it crashed.

I think it's a bug, you can try move your mouse to the edge of your screen, it may trigger this.

Will check this bug later.

Thank you very much, Wilfredo Velázquez-Rodríguez

**Comment by Zulu-Inuoe** [comment]
You're right. As soon as I moved the cursor to my second display, it showed a similar error (without pressing `Control-c`)

**Comment by VitoVan** [comment]
> You're right. As soon as I moved the cursor to my second display, it showed a similar error (without pressing `Control-c`)

That's because I am a poor guy who work with Windows only through VirtualBox which has no Second Display to test.

I'll try to get a decent Windows machine to work on this issue.

**Comment by VitoVan** [comment]
Hey Wilfredo Velázquez-Rodríguez, I finally got a decent Windows machine with second monitor, and repeated your situation.

It seems only happens when I place the second display on the right side of the main display. When moving mouse to the second display, the error will occur.

I tried place the second display on the up side of the main display, and move mouse to it, the Color Picker will show the red tip: "Come Back to Main Screen, Please". And that is supposed to be, 'cause I haven't put any effort on Multi-Display support.

Since we have not yet support Multi-Display, so I pushed a nasty commit to fix this problem: 56f5b2e73eccde7b02fbea464344dd505172662a

The main purpose of that commit is: If anything bad happened, blame the user, and tell them to try the main screen. 🤣

---

Here's the new release you may wanna try:

https://github.com/VitoVan/cl-pkr/releases/tag/1.1.0

---

And since this nasty release doesn't actually solve anything, I create another issue for this, and maybe one day we'll have the Multi-Display support #2.

**Comment by Zulu-Inuoe** [comment]
Hey @VitoVan ! Sorry about taking so long checking back in. I tried it and yep, works as you describe.
Honestly I think you're fine to close this issue since now it no longer hits an error. Instead, track further work on #2 instead.

Thanks!
